### ISSUE TITLE
Building Error. 

### ISSUE THREAD

**Issue by zero-kappa** [YZsZY/OctreeGS-Ubuntu-Viewer#1]
`cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="the-path-placed-libtorch/libtorch"`
Output:
CMake Error at src/CMakeLists.txt:81 (add_subdirectory):
add_subdirectory given source "core/assets" which is not an existing
directory.

**Comment by YZsZY** [comment]
Hello, the DCMAKE_PREFIX_PATH should be the path placed the libtorch, for example, I put the downloaded libtorch at the path: /home/zesongyang/library/libtorch, then input the command: 
```
cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/zesongyang/library/libtorch"
```

**Comment by zero-kappa** [comment]
@YZsZY Hello! I have already replaced the DCMAKE_PREFIX_PATH following your instruction. But the error seems to indicate that the ./src/core/assets are missing. Should I place the original SIBR_viewer's here?

**Comment by zero-kappa** [comment]
Or maybe can you provide a runnable file directly?

**Comment by YZsZY** [comment]
Let me check it

**Comment by YZsZY** [comment]
Hi, I accidentally add assets to the .gitignore file, the bug has been fixed, you can retry it～
